"""empty message

Revision ID: 08c0e05f4817
Revises: 
Create Date: 2021-04-21 21:06:15.403971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c0e05f4817'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('quotes_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quotes_value', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('quotes_id'),
    sa.UniqueConstraint('quotes_value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###
