"""comment

Revision ID: 4415bbeab4b7
Revises: 
Create Date: 2021-04-21 13:32:32.463560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4415bbeab4b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('quotes_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quotes_value', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('quotes_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###
